apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: python-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: sharonre0677/python-app

      dockerEnabled: true
      labels:
        - python-runner
        - self-hosted
